Repository ju-sung-kang/team4-mini-blog, pull requests merged in 2021-06, with the labels that each got.

#56 필요없는 코드 정리, footer 디자인 변경
  src/components/footer/index.jsx
  src/components/footer/styles.js
  src/components/header/index.jsx
  src/components/post-list/index.jsx
  src/page/main/index.jsx
  src/page/write-posting/index.jsx
Labels: front

#57 docs : readme 파일 수정
  README.md
Labels: documentation

#61 이미지 로드 에러시 기본이미지 띄우기
  src/components/footer/index.jsx
  src/components/header/index.jsx
Labels: back, front
